config/routes.rb
Rails.application.routes.draw do
  get '/login' ,to: 'sessions#new'
  post '/login' ,to: 'sessions#create'

  delete '/logout' ,to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/delete', to: 'users#destroy'

  get '/view', to: 'users#show'

  get 'static_pages/home'

  get '/about', to: 'static_pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :logged_in_yet?, only: [:home]
  before_action :loggout_user, only: [:home]
  layout 'about_layout', only: [:home]

  def home
    @users = User.all
  end

  def about
  end

  private

  def logged_in_yet?
  	if (logged_in?)
  		redirect_to @current_user
  	end
  end

  def loggout_user
      unless !logged_in?
        flash[:danger] = "Please log out."
        redirect_to current_user
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="jumbotron container" id="aboutme_div">
	<%= image_tag('avatar.jpg', id: 'about_ava', class: 'img-circle') %>
	<h1 class="welcome" style="background-color: white"> Hi, I'm Huy!</h1><br/>

	<p id="introduce">I design this blog to pratice my learning. 
	Besides, I love something colorful :v</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="jumbotron container" id="intro_div">
	<h1 class="welcome"> Welcome to my Blog!!!</h1><br/>
	<h4>I'm</h4>
	<h1 class="welcome">Gx</h1> <br/>
	<h4>I create this blog to</h4> 
	<h1 class="welcome">store your favorite pictures</h1>
</div>



<div id="login_div" class="container jumbotron">
	<span id="login_content">Wanna join???</span> <br/> <br/>
	<h2 class="login_content"><%= link_to "Log in", login_path, class:  
	"edit"  %></h2>
	<h2 class="login_content"><%= link_to "Sign up!!!", signup_path, class: "edit"  %></h2>
	
</div>

<div id="user_div" class="container jumbotron">
	<%= link_to image_tag("user.jpg", alt: "User icon", id: "img_user"), users_path  %>
	<p id="user_num"><%= @users.count %> members</p>
	
</div>

<div id="about_div" class="container jumbotron">
	<%= link_to image_tag("avatar.jpg", alt: "About icon", id: "img_about", class: "img-rounded"), about_path  %>
	<p id="aboutme">@About-me</p>

	
</div>