config/routes.rb
Rails.application.routes.draw do
  get '/login' ,to: 'sessions#new'
  post '/login' ,to: 'sessions#create'

  delete '/logout' ,to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/delete', to: 'users#destroy'

  get '/view', to: 'users#show'

  get 'static_pages/home'

  get '/about', to: 'static_pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts, dependent: :destroy
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

	scope :abc, -> { joins(:microposts).group("users.id").order("count(microposts) desc", "users.name desc") }
	attr_accessor :remember_token
	before_save {email.downcase!}
	validates :name, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 250},
										uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true

	mount_uploader :ava, PictureUploader
	validate  :ava_size
	# validates_integrity_of :ava

	 # Returns the hash digest of the given string.
	  def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
	  end

	  # Returns a random token.
	  def User.new_token
	    SecureRandom.urlsafe_base64
	  end

	  # Remembers a user in the database for use in persistent sessions.
	  def remember
	    self.remember_token = User.new_token
	    update_attribute(:remember_digest, User.digest(remember_token))
	  end

	  # Returns true if the given token matches the digest.
	  def authenticated?(remember_token)
	  	return false if remember_digest.nil?
	    BCrypt::Password.new(remember_digest).is_password?(remember_token)
	  end
	  # Forgets a user.
	def forget
	update_attribute(:remember_digest, nil)
	end
	# Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  # Returns a user's status feed.
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def self.get_user(user_a_id)
  	User.find_by(:id => user_a_id)
  end

  private

    # Validates the size of an uploaded picture.
    def ava_size
      if ava.size > 5.megabytes
        errors.add(:ava, "should be less than 5MB")
      end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show, :index, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :loggout_user, only: [:create, :new]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
    @users_top = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      log_in(@user)
      remember(@user)
      flash[:success] = "Welcome to the Photo Blog!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def show
    @user = User.find(params[:id])
    @micropost = current_user.microposts.build if logged_in?
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 15)
  end

  def following
    @title = "Following"
    @feed_items = current_user.feed.paginate(page: params[:feed_page], per_page: 10)
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:user_page], per_page: 6)
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 6)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :ava)
      
    end

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end

    def loggout_user
      unless !logged_in?
        flash[:danger] = "Please log out."
        redirect_to current_user
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary follow_button" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_newfeed.html.erb
<div class="post_div">
<li id="newfeed-<%= newfeed.id %>">
	<%= link_to newfeed.user.name, newfeed.user  %>
	<span>
		<% if  newfeed.picurl?%>
			<div id="links">
				<a href="<%= newfeed.picurl.url %>" data-gallery>
        <%= image_tag newfeed.picurl.url, class: 'post_pic' %>
    </a>
						
			</div>
		<% end %>
		
		
	</span>
<div class="post_hide">
	<span class="timestamp">
    Posted <%= time_ago_in_words(newfeed.created_at) %> ago.
  </span>
  <% if current_user == newfeed.user %>
     <span style="float: right;">
     	<%= link_to "delete", newfeed, method: :delete,
                                       data: { confirm: "You sure?" } %>
     </span> 
    <% end %>	
</div>
  

</li>
</div>

<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                	<%= link_to newfeed.user.name, newfeed.user  %>
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">
                    </h4>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn follow_button" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 jumbotron form_div">
    <h1>Edit profile</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.file_field :ava, class: 'form-control', id: 'ava_size', accept: 'image/jpeg,image/gif,image/png,image/jpg' %>

      <%= f.submit "Save change", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<% provide(:title, @title) %>

<div class="show_info_div">
	<% if @user.ava? %>
		<%= link_to image_tag(@user.ava.url, id: 'ava_img'), @user %>

		<% else %>
		<%= link_to image_tag('heroku.png', id: 'ava_img'), @user %>
	<% end %>

	<br/>

	<p id="show_name"><%= @user.name %></p>
	<p id="show_num">Pic num: <%= @user.microposts.count %></p>
	<p id="show_follower">
		<% @user ||= current_user %>
		<a href="<%= followers_user_path(@user) %>">
	    <strong id="followers">
	      <%= @user.followers.count %>
	    </strong>
	    followers
	  </a>
	</p>
	<p id="show_following">
		<a href="<%= following_user_path(@user) %>">
		    <strong id="following" class="stat">
		      <%= @user.following.count %>
		    </strong>
		    following
		  </a>
	</p>

</div>

<div class="row">
	<div class="container">
	
	<div class="show_member_div col-md-4">

	    
	</div>

	<div class="show_following_div container col-md-offset-8 ">
		<p style="text-align: center; font-size: xx-large; color: green; border-bottom: 2px dashed blue; margin-bottom: 20px;"> Follower list:</p>

		<% if @users.any? %>
	      	<ol class="users" style="word-spacing: 10px; list-style-type: none;">
			  <% @users.each do |user| %>
			    <li class="member_m">
			    	<% if user.ava? %>
			    	<div class="member_form">
			    		<div class="member_pic">
			    			<%= link_to image_tag(user.ava.url, id: 'ava_img2'), user  %>
			    			
			    		</div>
			    		<div class="member_name">
			    			<%= link_to user do %>
				      			<span id="member_name">
				      				<%= user.name %>
				      			</span>
				      		<% end %>
			    		</div>
			    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
			    	</div>
			    		
			      		
			      	<% else %>
			      		<div class="member_form">
				    		<div class="member_pic">
				    			<%= link_to image_tag('heroku.png', id: 'ava_img2'), user  %>
				    		</div>
				    		<div class="member_name">
			    				<%= link_to user do %>
					      			<span id="member_name">
					      				<%= user.name %>
					      			</span>
					      		<% end %>
				    		</div>
				    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
				    	</div>
			      		
			      		
			    	<% end %>
			      
			    </li>

			  <% end %>
			  <%= will_paginate %>
			</ol>



	      
	      <<!-- div class="pagi">
	      	<%= will_paginate %>
	      </div> -->
	    <% else %>
	    	<p style="text-align: center; color: red;"> Woahhhh!!</p>
	    <% end %>

	</div>

</div>
</div>

app/views/users/following.html.erb
<% provide(:title, @title) %>

<div class="show_info_div">
	<% if @user.ava? %>
		<%= link_to image_tag(@user.ava.url, id: 'ava_img'), @user %>

		<% else %>
		<%= link_to image_tag('heroku.png', id: 'ava_img'), @user %>
	<% end %>

	<br/>

	<p id="show_name"><%= @user.name %></p>
	<p id="show_num">Pic num: <%= @user.microposts.count %></p>
	<p id="show_follower">
		<% @user ||= current_user %>
		<a href="<%= followers_user_path(@user) %>">
	    <strong id="followers">
	      <%= @user.followers.count %>
	    </strong>
	    followers
	  </a>
	</p>
	<p id="show_following">
		<a href="<%= following_user_path(@user) %>">
		    <strong id="following" class="stat">
		      <%= @user.following.count %>
		    </strong>
		    following
		  </a>
	</p>

</div>

<div class="row">
	<div class="container">
	
	<div class="show_member_div col-md-4">
		<h1>Newfeed:</h1>
		<% if @feed_items.any? %>
		  <ol class="microposts">
		    <%= render partial: 'newfeed', collection: @feed_items, as: 'newfeed' %>
		  </ol>
		  <%= will_paginate @feed_items, :param_name => 'feed_page' %>
		<% end %>
	    
	</div>

	<div class="show_following_div container col-md-offset-8 ">
		<p style="text-align: center; font-size: xx-large; color: green; border-bottom: 2px dashed blue; margin-bottom: 20px;"> Following list:</p>

		<% if @users.any? %>
	      	<ol class="users" style="word-spacing: 10px; list-style-type: none;">
			  <% @users.each do |user| %>
			    <li class="member_m">
			    	<% if user.ava? %>
			    	<div class="member_form">
			    		<div class="member_pic">
			    			<%= link_to image_tag(user.ava.url, id: 'ava_img2'), user  %>
			    			
			    		</div>
			    		<div class="member_name">
			    			<%= link_to user do %>
				      			<span id="member_name">
				      				<%= user.name %>
				      			</span>
				      		<% end %>
			    		</div>
			    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
			    	</div>
			    		
			      		
			      	<% else %>
			      		<div class="member_form">
				    		<div class="member_pic">
				    			<%= link_to image_tag('heroku.png', id: 'ava_img2'), user  %>
				    		</div>
				    		<div class="member_name">
			    				<%= link_to user do %>
					      			<span id="member_name">
					      				<%= user.name %>
					      			</span>
					      		<% end %>
				    		</div>
				    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
				    	</div>
			      		
			      		
			    	<% end %>
			      
			    </li>

			  <% end %>
			  <%= will_paginate @users, :param_name => 'user_page' %>
			</ol>



	      
	      <<!-- div class="pagi">
	      	<%= will_paginate %>
	      </div> -->
	    <% else %>
	    	<p style="text-align: center; color: red;"> Woahhhh!!</p>
	    <% end %>

	</div>

</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Members') %>
<h1 style="color: black; background-color: white;">Members</h1>

<div class="row">
	<div class="container">
	
	<div class="show_member_div col-md-4">

	    <% if @users.any? %>
	    <%= will_paginate %>
	      	<ul class="users" style="word-spacing: 10px; list-style-type: none;">
			  <% @users.each do |user| %>
			    <li class="member_m">
			    	<% if user.ava? %>
			    	<div class="member_form">
			    		<div class="member_pic">
			    			<%= link_to image_tag(user.ava.url, id: 'ava_img2'), user  %>
			    			
			    		</div>
			    		<div class="member_name">
			    			<%= link_to user do %>
				      			<span id="member_name">
				      				<%= user.name %>
				      			</span>
				      		<% end %>
			    		</div>
			    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
			    		<div class="member_delete">
		    				<% if current_user.admin? && current_user != @user %>
						    <%= link_to "delete", user, method: :delete,
						                                  data: { confirm: "You sure?" } %>
						  <% end %>
			    		</div>

			    	</div>
			    		
			      		
			      	<% else %>
			      		<div class="member_form">
				    		<div class="member_pic">
				    			<%= link_to image_tag('heroku.png', id: 'ava_img2'), user  %>
				    		</div>
				    		<div class="member_name">
			    				<%= link_to user do %>
					      			<span id="member_name">
					      				<%= user.name %>
					      			</span>
					      		<% end %>
				    		</div>
				    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
				    		<div class="member_delete">
		    				<% if current_user.admin? && current_user != @user %>
						    <%= link_to "delete", user, method: :delete,
						                                  data: { confirm: "You sure?" } %>
						  <% end %>
			    		</div>
				    	</div>
			      		
			      		
			    	<% end %>
			      
			    </li>

			  <% end %>
			</ul>



	      
	      <<!-- div class="pagi">
	      	<%= will_paginate %>
	      </div> -->
	    <% else %>
	    	<p style="text-align: center; color: red;"> Woahhhh!!</p>
	    <% end %>
	    <%= will_paginate %>
	</div>

	<div class="show_top10_div container col-md-offset-8 ">
		<p style="text-align: center; font-size: xx-large; color: green; border-bottom: 2px dashed blue; margin-bottom: 20px;"> Top 5 users:</p>

		<% if @users.any? %>
	      	<ol class="users" style="word-spacing: 10px; list-style-type: none;">
			  <% @users_top.abc.limit(5).each do |user| %>
			    <li class="member_m">
			    	<% if user.ava? %>
			    	<div class="member_form">
			    		<div class="member_pic">
			    			<%= link_to image_tag(user.ava.url, id: 'ava_img2'), user  %>
			    			
			    		</div>
			    		<div class="member_name">
			    			<%= link_to user do %>
				      			<span id="member_name">
				      				<%= user.name %>
				      			</span>
				      		<% end %>
			    		</div>
			    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
			    	</div>
			    		
			      		
			      	<% else %>
			      		<div class="member_form">
				    		<div class="member_pic">
				    			<%= link_to image_tag('heroku.png', id: 'ava_img2'), user  %>
				    		</div>
				    		<div class="member_name">
			    				<%= link_to user do %>
					      			<span id="member_name">
					      				<%= user.name %>
					      			</span>
					      		<% end %>
				    		</div>
				    		<div class="member_follow">
			    				<span>

			    					<strong id="followers">
								      followers: <%= user.followers.count %>
								    </strong>
			    				</span>
				    		</div>
				    	</div>
			      		
			      		
			    	<% end %>
			      
			    </li>

			  <% end %>
			</ol>



	      
	      <<!-- div class="pagi">
	      	<%= will_paginate %>
	      </div> -->
	    <% else %>
	    	<p style="text-align: center; color: red;"> Woahhhh!!</p>
	    <% end %>

	</div>

</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'New') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 jumbotron form_div">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.file_field :ava, class: 'form-control', id: 'ava_size', accept: 'image/jpeg,image/gif,image/png,image/jpg' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'My Blog') %>

	

<div class="show_info_div">
	<% if @user.ava? %>
		<%= link_to image_tag(@user.ava.url, id: 'ava_img'), @user %>

		<% else %>
		<%= link_to image_tag('heroku.png', id: 'ava_img'), @user %>
	<% end %>

	<br/>

	<p id="show_name"><%= @user.name %></p>
	<p id="show_num">Pic num: <%= @user.microposts.count %></p>
	<p id="show_follower">
		<% @user ||= current_user %>
		<a href="<%= followers_user_path(@user) %>">
	    <strong id="followers">
	      <%= @user.followers.count %>
	    </strong>
	    followers
	  </a>
	</p>
	<p id="show_following">
		<a href="<%= following_user_path(@user) %>">
		    <strong id="following" class="stat">
		      <%= @user.following.count %>
		    </strong>
		    following
		  </a>
	</p>

</div>
<% if current_user == @user %>
     <div class="show_footer_div">
		<p style="color: red">Upload new picture!</p>
		<%= form_for(@micropost) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>
		  <%= hidden_field_tag 'micropost[picurl]' %>
		  <%= f.file_field :picurl, class: 'form-control', id: 'ava_size', accept: 'image/jpeg,image/gif,image/png,image/jpg', require: true %>

		  <%= f.submit "Post", class: "btn btn-primary" %>
		<% end %>

	</div>
	<% else %>
		<div class="show_footer_div">
		
			<%= render 'follow_form' %>
		</div>
    <% end %>

<div class="row">
	<div class="show_content_div container">
	    <% if @user.microposts.any? %>
	      <div class="picpic">
	      	<ul style="list-style-type: none">
	      	
	        	<%= render @microposts %>        	
	    	
	      	</ul>

	      </div>

	      
	      <div class="pagi">
	      	<%= will_paginate @microposts %>
	      </div>
	    <% else %>
	    	<p style="text-align: center; color: red;"> Enjoy, post some your favourite picture!!!</p>
	    <% end %>

	</div>

</div>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>