config/routes.rb
Rails.application.routes.draw do
  get '/login' ,to: 'sessions#new'
  post '/login' ,to: 'sessions#create'

  delete '/logout' ,to: 'sessions#destroy'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/delete', to: 'users#destroy'

  get '/view', to: 'users#show'

  get 'static_pages/home'

  get '/about', to: 'static_pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="nav navbar-fixed-bottom">
	<div class="container">
		<nav>
			
				<div id="footer_div">
					<ul class="nav navbar-nav navbar-left">
						<li>
							<%= link_to image_tag("avatar.jpg", alt: "Avatar", class: "img-circle footer_img"),
		            'https://www.facebook.com/giahuy.truong.773' %>
						</li>

						<li>
							<%= link_to image_tag("GitHub.png", alt: "Github", class: "img-circle footer_img"),
		            'https://github.com/huygia1997/Photo_Blog' %>
						</li>

						<li>
							<%= link_to image_tag("heroku.png", alt: "Heroku", class: "img-circle footer_img"),
		            'https://dashboard.heroku.com/apps/photo-blog-gx' %>
						</li>
					</ul>
				</div>	

				<div class="nav navbar-nav navbar-right">
					<a id="back_to_top" href="" class="btn btn-primary btn-lg back-to-top" role="button">
						<span class="glyphicon glyphicon-chevron-up">
							
						</span>
					</a>
				</div>							
			
		</nav>
	</div>
	
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Photo Blog", root_path , id: "logo"  %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to users_path do %>
						<span class="glyphicon glyphicon-user"></span>
					<% end %>
				</li>

				<li><span style="font-size: xx-large; color: red; pointer-events: none;">|</span></li>

				<li>
					<%= link_to about_path  do %>
						<span class="glyphicon glyphicon-info-sign"></span>
					<% end %>
				</li>

				<li><span style="font-size: xx-large; color: red; pointer-events: none;">|</span></li>
				<% if logged_in? %>
					<li>
						<%= link_to root_path do %>
							<span id="drop_trigger" class="glyphicon glyphicon-edit">
								<div id="drop_show"> 
									<div>
										<%= link_to "Profile", root_path, class: "drop_text" %>
									</div>

									<div>
										<%= link_to "Edit", edit_user_path(current_user), class: "drop_text" %>
									</div>

									<div>
										<%= link_to "Log out", logout_path, method: :delete,class: "drop_text" %>
									</div>

									
								</div>
							</span>
						<% end %>
					</li>
				<% else %>
					<li>
						<%= link_to login_path do  %>
							<span class="glyphicon glyphicon-log-in">
						<% end %>
					</li>	
				<% end %>

				
													
			</ul>
			<form class="navbar-form navbar-nav" id="search_form" action="/">
				<div class="form-group">
			        <input type="text" id="search_text" placeholder="Search">
			    </div>
			    <button type="submit" id="search_button" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
			</form>
		</nav>
	</div>	

</header>

app/views/layouts/about_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <%= csrf_meta_tags %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
        <div class="back_pic_about container">
          <div class="container">

            <%= render 'layouts/header' %>
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
          </div>
        </div>
    </div>
  	
  	
  	
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <%= csrf_meta_tags %>
    <!-- <meta name="turbolinks-cache-control" content="no-cache"> -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
        <div class="back_pic container">
          <div class="container">

            <%= render 'layouts/header' %>
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
          </div>
        </div>
    </div>
  	
  	
  	
    
  </body>
</html>

app/views/layouts/show_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <%= csrf_meta_tags %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
        <div class="back_pic container">
          <div class="container">

            <%= render 'layouts/header' %>
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
          </div>
        </div>
    </div>
  	
  	
  	
    
  </body>
</html>